name: Update README

on:
  push:
    branches:
      - main  # Update this if your main branch has a different name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run script
      run: |
        ./update_Readme.bat
      shell: cmd
