name: Update README

on:
  push:
    branches:
      - main  # Update this if your main branch has a different name

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v1
      with:
        submodules: 'recursive'

    - name: Use Node.js 16
      uses: actions/setup-node@v4
      with:
        node-version: '16'
